ALTER TABLE ANIMAL_SHELTER.ANIMAL_INS DISABLE KEYS;
ALTER TABLE ANIMAL_SHELTER.ANIMAL_OUTS DISABLE KEYS;
LOAD DATA LOCAL INFILE './dataset/animal_in.csv' INTO TABLE ANIMAL_SHELTER.ANIMAL_INS FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE './dataset/animal_out.csv' INTO TABLE ANIMAL_SHELTER.ANIMAL_OUTS FIELDS TERMINATED BY ",";
ALTER TABLE ANIMAL_SHELTER.ANIMAL_INS ENABLE KEYS;
ALTER TABLE ANIMAL_SHELTER.ANIMAL_OUTS ENABLE KEYS;
